spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: mousesun
    password: mousesun
    url: jdbc:mysql://47.98.216.192/canteen?serverTimezone=UTC
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null
server:
  servlet:
    context-path: /sell
  port: 8080
#logging:
#  pattern:
#    console: "%d-%msg%n"
#  file:
#    path: sell/log